-- MySQL Script generated by MySQL Workbench
-- Sat Jun 17 15:14:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema willchair
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema willchair
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `willchair` DEFAULT CHARACTER SET utf8 ;
USE `willchair` ;

-- -----------------------------------------------------
-- Table `willchair`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `willchair`.`User` (
  `user_cod` INT NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(100) NOT NULL,
  `user_level` INT NOT NULL,
  `user_phone` VARCHAR(45) NULL,
  `user_houseNum` VARCHAR(10) NULL,
  `user_CEP` VARCHAR(20) NULL,
  `user_nota` INT NULL,
  `user_name` VARCHAR(50) NULL,
  `user_img` MEDIUMBLOB NULL,
  PRIMARY KEY (`user_cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `willchair`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `willchair`.`Product` (
  `prod_cod` INT NOT NULL AUTO_INCREMENT,
  `prod_img` MEDIUMBLOB NULL,
  `prod_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`prod_cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `willchair`.`Offer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `willchair`.`Offer` (
  `ofr_cod` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ofr_name` VARCHAR(45) NOT NULL,
  `ofr_type` VARCHAR(45) NOT NULL,
  `ofr_desc` MEDIUMTEXT NULL,
  `ofr_value` DATETIME NULL,
  `ofr_status` VARCHAR(45) NOT NULL,
  `ofr_postDate` DATE NULL,
  `User_user_cod` INT NOT NULL REFERENCES `willchair`.`User` (`user_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  `Product_prod_cod` INT NOT NULL REFERENCES `willchair`.`Product` (`prod_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `willchair`.`Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `willchair`.`Chat` (
  `chat_cod` INT NOT NULL AUTO_INCREMENT,
  `Offer_ofr_cod` INT NOT NULL REFERENCES `willchair`.`Offer` (`ofr_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  PRIMARY KEY (`chat_cod`)
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `willchair`.`Mesage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `willchair`.`Mesage` (
  `msg_cod` INT NOT NULL AUTO_INCREMENT,
  `msg_content` TINYTEXT NOT NULL,
  `User_user_cod` INT NOT NULL   REFERENCES `willchair`.`User` (`user_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  `Chat_chat_cod` INT NOT NULL REFERENCES `willchair`.`Chat` (`chat_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  PRIMARY KEY (`msg_cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `willchair`.`Denounce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `willchair`.`Denounce` (
  `den_cod` INT NOT NULL AUTO_INCREMENT,
  `den_content` TINYTEXT NOT NULL,
  `den_date` DATE NOT NULL,
  `User_user_cod` INT NOT NULL  REFERENCES `willchair`.`User` (`user_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  `Offer_ofr_cod` INT NOT NULL REFERENCES `willchair`.`Offer` (`ofr_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  PRIMARY KEY (`den_cod`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
